### ISSUE TITLE
Support HiDPI displays

### ISSUE THREAD

**Issue by hai-ld** [Busimus/cutelog#1]
Currently, at default, cutelog looks like this on my display (3840x2160, 2x scale)

![screenshot from 2018-01-12 14-44-09](https://user-images.githubusercontent.com/1579471/34864527-49c99d76-f7a7-11e7-8cca-03796792a1a3.png)

It gets worse on Settings dialog

![screenshot from 2018-01-12 14-46-54](https://user-images.githubusercontent.com/1579471/34864580-824bfc48-f7a7-11e7-8b84-ec38d453b860.png)

Thanks for your awesome work! ;)

**Comment by Busimus** [comment]
Unfortunately I have no high DPI displays at my disposal, but I'll try to figure something out.

The only thing I know about Qt and high DPI is that `QT_SCALE_FACTOR` environment variable is a thing. 
If that isn't what you meant by "2x scale" then try launching cutelog like this: `QT_SCALE_FACTOR=2 cutelog`.

**Comment by hai-ld** [comment]
Thanks for the input. I tried `QT_SCALE_FACTOR` but it did a different thing. Apparently the correct environment variable to set is `QT_SCREEN_SCALE_FACTORS` http://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt (2 in my case). You might want to add this to the README file.

**Comment by Busimus** [comment]
Could you please try installing the git version (`pip install --upgrade git+https://github.com/busimus/cutelog.git`) and see what kind of results you get by default with no variables? I enabled automatic scaling.

**Comment by hai-ld** [comment]
It works!

![screenshot from 2018-01-12 15-53-15](https://user-images.githubusercontent.com/1579471/34866896-bce2826a-f7b0-11e7-9a11-be919361194f.png)
![screenshot from 2018-01-12 15-53-35](https://user-images.githubusercontent.com/1579471/34866908-c7dbc938-f7b0-11e7-8ac5-fc82af4b8398.png)

Thanks for your very swift response ;)
