### ISSUE TITLE
Connecting to python script running in VPS

### ISSUE THREAD

**Issue by arul67800** [busimus/cutelog#21]
if i add the IP adress of my vps , it throws a message "this address is not available" ...
Is there any way to connect to external server??

**Comment by busimus** [comment]
You got it backwards. The program running on your VPS will be establishing the connection to the log server that's running inside of cutelog.

So you should leave "Server listen address" as 0.0.0.0, make sure the listen port is forwarded in your router to your computer, and then enter your global IP address and the forwarded port in the arguments of the `SocketHandler`.

**Comment by arul67800** [comment]
confused ...........can you please elaborate it .
when i want cutelog in same computer its working...i jus want to listen to a remote log in my pc...i couldnt understand the steps

**Comment by arul67800** [comment]
how to forward the listen port to my computer
