### ISSUE TITLE
Feature request: Close all old tabs

### ISSUE THREAD

**Issue by sparvanders** [busimus/cutelog#24]
A button "Close other tabs" that closes all but the active tab. This feature exists in for example Eclipse.

**Background:** When I develop a program, I often restart the program to load changes. This will (very reasonably) create a new tab in Cutelog. But often I'm not interested in the old tabs and I just want to close them all. This could be 20 tabs so it's a lot of clicking.

For more control, an option "close all to the left" could close all but a set of most recent tabs.

**Comment by busimus** [comment]
You currently have two options:

1. Hold down or mash Ctrl+W (common shortcut to close tabs in browsers and etc.)
2. Enable "Single tab mode" in the "File" menu. If you're developing one program at a time and don't mind the records from previous runs remaining on the screen, this could work for you.

If this isn't satisfactory I'll look into adding a context menu to tabs.
