### ISSUE TITLE
Feature request: Remove the console

### ISSUE THREAD

**Issue by ba361006** [busimus/cutelog#26]
Hi there!
Is there any way to remove the console window?

![image](https://user-images.githubusercontent.com/52664844/176989202-8f1f291d-c09b-4225-8908-838a1c745516.png)

**Comment by busimus** [comment]
One way is to run it from another console using the `cutelog` command. But if you want something double-clickable with no console at all, then my only idea is to create a `cutelog.vbs` script with this line: 
```vbs
CreateObject("Wscript.Shell").Run "D:\Tools\Coding\Python\Scripts\cutelog.exe",0,True
```
There's probably a better way, but I'm not very familiar with Windows.
