### ISSUE TITLE
Decrease UI size on Windows

### ISSUE THREAD

**Issue by raelb** [busimus/cutelog#27]
Hi,
Thanks for your project. I'm running on Windows with 150% scaling, and the entire cutelog interface is enlarged. Is there a way to decrease the UI size as a whole?

See screenshot, with notepad++ in the background, showing normal appearance of app menu:

![image](https://user-images.githubusercontent.com/13108198/178155556-947ab79e-aad9-4629-8c96-a445b2a0465e.png)

Thanks

**Comment by busimus** [comment]
You can change this with an environment variable. Before starting `cutelog`, set it like this:
* If you're using PowerShell: `$Env:QT_AUTO_SCREEN_SCALE_FACTOR=0`
* If you're using cmd.exe: `set QT_AUTO_SCREEN_SCALE_FACTOR=0`
This should have the desired effect, but you'll probably also want to adjust font sizes in the settings of cutelog.
