### ISSUE TITLE
Conflicting Licenses

### ISSUE THREAD

**Issue by stephengaito** [busimus/cutelog#30]
Hello, I am exploring a simple "wrapper" of cutelog to add "actions" (such as opening the source file to the location of a logged error).

While I am attempting to provide a clean sub-classing of qutelog classes (with possible monkey-patching -- if needed), there are a couple of cutelog files (such as `__main__.py`) which I need to copy and then slightly alter.

Cutelog's "Main" LICENSE is currently MIT (from commit f9e7ce11fa8e10033eaeb98fe5099b6e88323fc5 on 5 May 2019 at 17:28)

Unfortunately your UI's about box still lists your LICENSE as GPLv3.

My goal here is to make my project's license the same as your (current?) license, so that my changes, should they prove useful, may (some day) be incorporated directly into the main cutelog project.

Which LICENSE is the currently correct license, and which license should I use for my project ( https://github.com/stephengaito/cutelogActions )?

Regards,
Stephen Gaito

**Comment by busimus** [comment]
The about box doesn't actually state the license of the project itself, only its dependencies and texts of their licenses. The project's license is MIT, I should probably add a line to the box that says this.

And your license is up to you. Whatever is compatible with MIT, I guess.

**Comment by stephengaito** [comment]
@busimus Many thanks for the clarification. If you are using MIT, I will as well.

A line in the about box would be helpful... if and when it happens.

Your tool (at first play) *is* very nice. Thank you for the work!
