### ISSUE TITLE
Ability to show multiline messages when not in extra mode

### ISSUE THREAD

**Issue by csm10495** [busimus/cutelog#33]
Right now when i have a message that has newlines in it, it gets replaced with ... 

Can we have an option to display the full log even if it has newlines?

**Comment by busimus** [comment]
Instead of adding multiline messages, I added a word wrap toggle. Solves the same problem and a bunch more, though it has a performance penalty. Try it out:
```
pip install git+https://github.com/busimus/cutelog.git@word_wrap
```

**Comment by csm10495** [comment]
Nice! Works well for me. Thanks! Hopefully it can get merged.
