### ISSUE TITLE
Customize host and port

### ISSUE THREAD

**Issue by JosephP91** [busimus/cutelog#36]
Is it possible to customize the port and the host from the command line?

**Comment by busimus** [comment]
I just added command line argument parsing to the master branch. Try it by installing cutelog with:
```
pip install git+https://github.com/busimus/cutelog.git
```

You can now override the listen address with `--listen_host my_host --listen_port 8080`, as well as any other settings and also load saved log files by passing their paths (see `--help` for all options).

**Comment by JosephP91** [comment]
Great! I'll give it a try

**Comment by JosephP91** [comment]
Working like a charm! Do you have a date for the next release?

**Comment by busimus** [comment]
It's out. Hopefully nothing broke in the process.
