### ISSUE TITLE
Requirement qtpy is not installed by pip

### ISSUE THREAD

**Issue by bergmansj** [busimus/cutelog#9]
`pip install cutelog` does not install the `qtpy` package (it does install PyQt5).

This results in a `ModuleNotFoundError: No module named 'qtpy'` when trying to start cutelog.

It seems just to be a missing dependency in the package info, because after a `pip install qtpy` things are ok.

**Comment by busimus** [comment]
Well, that was dumb. Thanks for pointing it out.
